export const currencies = [
  { code: 'KZT', name: 'Казахстанский тенге' },
  { code: 'RUB', name: 'Российский рубль' },
  { code: 'USD', name: 'Доллар США' },
  { code: 'EUR', name: 'Евро' },
  { code: 'GBP', name: 'Британский фунт' },
  { code: 'CNY', name: 'Китайский юань' },
  { code: 'JPY', name: 'Японская иена' },
  { code: 'KRW', name: 'Южнокорейская вона' },
  { code: 'TRY', name: 'Турецкая лира' },
  { code: 'AED', name: 'Дирхам ОАЭ' },
  { code: 'CHF', name: 'Швейцарский франк' },
  { code: 'CAD', name: 'Канадский доллар' },
  { code: 'AUD', name: 'Австралийский доллар' },
  { code: 'UZS', name: 'Узбекский сум' },
  { code: 'KGS', name: 'Кыргызский сом' },
  { code: 'GEL', name: 'Грузинский лари' },
  { code: 'INR', name: 'Индийская рупия' },
  { code: 'PLN', name: 'Польский злотый' },
] as const;
